### ISSUE TITLE
4.4.1 net::ERR_INCOMPLETE_CHUNKED_ENCODING

### ISSUE THREAD

**Issue by free302** [NonFactors/MVC6.Grid#198]
I'm not sure this error caused by mvc-grid or by chrome.
When sorting a column includes empty string by clicking the column header
the page hung and the message  net::ERR_INCOMPLETE_CHUNKED_ENCODING appeared
on chrome console.
Chrome console showed:
mvc-grid.js:199 
GET http://192.168.0.2/Users/Index?sort=employer.comm-name&order=asc net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)

Code @mvc-grid.js:199 is 
window.location.href = window.location.origin + window.location.pathname + grid.query;

I found the navigation property 'employer' was null.
So employer.comm-name may throws null reference exception.
When the property 'employer' was filled with a valid value, the error message gone.

[192.168.0.2-1560089369379.log](https://github.com/NonFactors/MVC6.Grid/files/3269622/192.168.0.2-1560089369379.log)

**Comment by Muchiachio** [comment]
This is mostly likely asp net error in a code, you can most likely see a stack trace in the logs.

**Comment by free302** [comment]
1) Without query string (http://192.168.0.2/users/Index), it's ok.
2) With query string (http://192.168.0.2/users/Index/?sort=employer.comm-name&order=asc),
unhandled exception has occurred. (refer to logs followed)
3) By setting  'employer' with a blank instance(with null member), the exception not thrown.

Stack trace in the logs:

fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , Users )
   at System.Linq.EnumerableSorter'2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter'1.ComputeMap(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter'1.Sort(TElement[] elements, Int32 count, Int32 minIdx, Int32 maxIdx)
   at System.Linq.OrderedEnumerable'1.GetEnumerator(Int32 minIdx, Int32 maxIdx)+MoveNext()
   at System.Collections.Generic.List'1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable'1 source)
   at NonFactors.Mvc.Grid.GridRows'1.GetEnumerator()
   at System.Linq.Enumerable.Any[TSource](IEnumerable'1 source)
   at AspNetCore.Views_Shared_MvcGrid__Grid.ExecuteAsync() in **E:\...\WebApp\Views\Shared\MvcGrid\_Grid.cshtml:line 120**
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   ...
   **at NonFactors.Mvc.Grid.HtmlGrid'1.WriteTo(TextWriter writer, HtmlEncoder encoder)**
   ...
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

#### Code  @_Grid.cshtml:line 120 :
`<tbody>`
`           @if (Model.Rows.Any())`
`            {`

**Comment by Muchiachio** [comment]
You can't sort on nullable relations, you can try that with linq and you will get the same result on your data
```C#
Model.OrderBy(model => model.Employer.CommName);
```
The solution would be to map your relations to single properties like so
```C#
.Select(model => new ViewModel
{
    EmployerCommName = Employer.CommName
})
```
